services:
  redis:
    image: redis:7-alpine
    container_name: planapi-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build:
      context: .
    image: planapi:dev
    container_name: planapi-api
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__Redis: "redis:6379"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - redis
    restart: unless-stopped
  
  Elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.4
    environment:
      - discovery.type=single-node        # one node, no cluster election
      - xpack.security.enabled=false       # disable auth for local demo
      - ES_JAVA_OPTS=-Xms512m -Xmx512m     # cap heap so it doesn't eat your machine
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  Kibana:
    image: docker.elastic.co/kibana/kibana:9.4.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
        Elasticsearch:
          condition: service_healthy         # wait for ES to be ready first

  RabbitMQ:
    image: rabbitmq:3-management            # -management gives you the web UI
    ports:
      - "5672:5672"                         # broker port (your app connects here)
      - "15672:15672"                       # management UI (browser: localhost:15672)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
